// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwaigmzevohdywsvdgly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3YWlnbXpldm9oZHl3c3ZkZ2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDMyNzEsImV4cCI6MjA2NTU3OTI3MX0.8zBiKmo0b3H6p8CAUUPjCGiockM06Zuxd_eDhEb1L7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);